base:
  project: titanic
  random_state: 514
  target_col: TARGET

data_source:
  s3_source: s3://$(BUCKET)/data/*.csv

load_data:
  raw_dataset_csv: data/raw/*.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
model_dir: data/saved_models

reports:
  params: logs/params.json
  scores: logs/scores.json